// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ExplosionsHandle : RemoteTableHandle<EventContext, Explosion>
        {
            protected override string RemoteTableName => "Explosions";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Explosion row) => row.Id;

                public IdUniqueIndex(ExplosionsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ExplosionsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Explosion row) => row.Id;
        }

        public readonly ExplosionsHandle Explosions;
    }
}
