// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PhysicsScheduleHandle : RemoteTableHandle<EventContext, PhysicsSchedule>
        {
            protected override string RemoteTableName => "physics_schedule";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PhysicsSchedule row) => row.Id;

                public IdUniqueIndex(PhysicsScheduleHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal PhysicsScheduleHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(PhysicsSchedule row) => row.Id;
        }

        public readonly PhysicsScheduleHandle PhysicsSchedule;
    }
}
