// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WormsHandle : RemoteTableHandle<EventContext, Worm>
        {
            protected override string RemoteTableName => "Worms";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Worm row) => row.Id;

                public IdUniqueIndex(WormsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class PlayerIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(Worm row) => row.PlayerId;

                public PlayerIdIndex(WormsHandle table) : base(table) { }
            }

            public readonly PlayerIdIndex PlayerId;

            internal WormsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(Worm row) => row.Id;
        }

        public readonly WormsHandle Worms;
    }
}
