// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Config
    {
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "MapWidth")]
        public int MapWidth;
        [DataMember(Name = "MapHeight")]
        public int MapHeight;
        [DataMember(Name = "RandomSeed")]
        public int RandomSeed;

        public Config(
            uint Id,
            int MapWidth,
            int MapHeight,
            int RandomSeed
        )
        {
            this.Id = Id;
            this.MapWidth = MapWidth;
            this.MapHeight = MapHeight;
            this.RandomSeed = RandomSeed;
        }

        public Config()
        {
        }
    }
}
