// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Entity
    {
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "Position")]
        public DbVector2 Position;
        [DataMember(Name = "Velocity")]
        public DbVector2 Velocity;
        [DataMember(Name = "Rotation")]
        public float Rotation;

        public Entity(
            uint Id,
            DbVector2 Position,
            DbVector2 Velocity,
            float Rotation
        )
        {
            this.Id = Id;
            this.Position = Position;
            this.Velocity = Velocity;
            this.Rotation = Rotation;
        }

        public Entity()
        {
            this.Position = new();
            this.Velocity = new();
        }
    }
}
