// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Explosion
    {
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "Position")]
        public DbVector2 Position;
        [DataMember(Name = "Radius")]
        public float Radius;
        [DataMember(Name = "BaseDamage")]
        public float BaseDamage;
        [DataMember(Name = "DamageFalloff")]
        public float DamageFalloff;

        public Explosion(
            uint Id,
            DbVector2 Position,
            float Radius,
            float BaseDamage,
            float DamageFalloff
        )
        {
            this.Id = Id;
            this.Position = Position;
            this.Radius = Radius;
            this.BaseDamage = BaseDamage;
            this.DamageFalloff = DamageFalloff;
        }

        public Explosion()
        {
            this.Position = new();
        }
    }
}
