// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Game
    {
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "Map")]
        public System.Collections.Generic.List<byte> Map;
        [DataMember(Name = "CurrentState")]
        public byte CurrentState;
        [DataMember(Name = "NextState")]
        public byte NextState;
        [DataMember(Name = "GameIsStable")]
        public bool GameIsStable;
        [DataMember(Name = "PlayerActionComplete")]
        public bool PlayerActionComplete;

        public Game(
            uint Id,
            System.Collections.Generic.List<byte> Map,
            byte CurrentState,
            byte NextState,
            bool GameIsStable,
            bool PlayerActionComplete
        )
        {
            this.Id = Id;
            this.Map = Map;
            this.CurrentState = CurrentState;
            this.NextState = NextState;
            this.GameIsStable = GameIsStable;
            this.PlayerActionComplete = PlayerActionComplete;
        }

        public Game()
        {
            this.Map = new();
        }
    }
}
