// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Missile
    {
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "PlayerId")]
        public uint PlayerId;

        public Missile(
            uint Id,
            uint PlayerId
        )
        {
            this.Id = Id;
            this.PlayerId = PlayerId;
        }

        public Missile()
        {
        }
    }
}
