// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddEntityHandler(ReducerEventContext ctx, Entity entity);
        public event AddEntityHandler? OnAddEntity;

        public void AddEntity(Entity entity)
        {
            conn.InternalCallReducer(new Reducer.AddEntity(entity), this.SetCallReducerFlags.AddEntityFlags);
        }

        public bool InvokeAddEntity(ReducerEventContext ctx, Reducer.AddEntity args)
        {
            if (OnAddEntity == null) return false;
            OnAddEntity(
                ctx,
                args.Entity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddEntity : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity")]
            public Entity Entity;

            public AddEntity(Entity Entity)
            {
                this.Entity = Entity;
            }

            public AddEntity()
            {
                this.Entity = new();
            }

            string IReducerArgs.ReducerName => "AddEntity";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddEntityFlags;
        public void AddEntity(CallReducerFlags flags) => AddEntityFlags = flags;
    }
}
