// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClearEntitiesHandler(ReducerEventContext ctx);
        public event ClearEntitiesHandler? OnClearEntities;

        public void ClearEntities()
        {
            conn.InternalCallReducer(new Reducer.ClearEntities(), this.SetCallReducerFlags.ClearEntitiesFlags);
        }

        public bool InvokeClearEntities(ReducerEventContext ctx, Reducer.ClearEntities args)
        {
            if (OnClearEntities == null) return false;
            OnClearEntities(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClearEntities : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "ClearEntities";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ClearEntitiesFlags;
        public void ClearEntities(CallReducerFlags flags) => ClearEntitiesFlags = flags;
    }
}
