// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateMapHandler(ReducerEventContext ctx);
        public event CreateMapHandler? OnCreateMap;

        public void CreateMap()
        {
            conn.InternalCallReducer(new Reducer.CreateMap(), this.SetCallReducerFlags.CreateMapFlags);
        }

        public bool InvokeCreateMap(ReducerEventContext ctx, Reducer.CreateMap args)
        {
            if (OnCreateMap == null) return false;
            OnCreateMap(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateMap : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "CreateMap";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateMapFlags;
        public void CreateMap(CallReducerFlags flags) => CreateMapFlags = flags;
    }
}
