// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteEntityByIdHandler(ReducerEventContext ctx, uint entityId);
        public event DeleteEntityByIdHandler? OnDeleteEntityById;

        public void DeleteEntityById(uint entityId)
        {
            conn.InternalCallReducer(new Reducer.DeleteEntityById(entityId), this.SetCallReducerFlags.DeleteEntityByIdFlags);
        }

        public bool InvokeDeleteEntityById(ReducerEventContext ctx, Reducer.DeleteEntityById args)
        {
            if (OnDeleteEntityById == null) return false;
            OnDeleteEntityById(
                ctx,
                args.EntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteEntityById : Reducer, IReducerArgs
        {
            [DataMember(Name = "entityId")]
            public uint EntityId;

            public DeleteEntityById(uint EntityId)
            {
                this.EntityId = EntityId;
            }

            public DeleteEntityById()
            {
            }

            string IReducerArgs.ReducerName => "DeleteEntityByID";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeleteEntityByIdFlags;
        public void DeleteEntityById(CallReducerFlags flags) => DeleteEntityByIdFlags = flags;
    }
}
