// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void HandlePhysicsHandler(ReducerEventContext ctx, PhysicsSchedule schedule);
        public event HandlePhysicsHandler? OnHandlePhysics;

        public void HandlePhysics(PhysicsSchedule schedule)
        {
            conn.InternalCallReducer(new Reducer.HandlePhysics(schedule), this.SetCallReducerFlags.HandlePhysicsFlags);
        }

        public bool InvokeHandlePhysics(ReducerEventContext ctx, Reducer.HandlePhysics args)
        {
            if (OnHandlePhysics == null) return false;
            OnHandlePhysics(
                ctx,
                args.Schedule
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HandlePhysics : Reducer, IReducerArgs
        {
            [DataMember(Name = "schedule")]
            public PhysicsSchedule Schedule;

            public HandlePhysics(PhysicsSchedule Schedule)
            {
                this.Schedule = Schedule;
            }

            public HandlePhysics()
            {
                this.Schedule = new();
            }

            string IReducerArgs.ReducerName => "HandlePhysics";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags HandlePhysicsFlags;
        public void HandlePhysics(CallReducerFlags flags) => HandlePhysicsFlags = flags;
    }
}
