// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void HandlePhysicsHandler(ReducerEventContext ctx, float elapsedTime);
        public event HandlePhysicsHandler? OnHandlePhysics;

        public void HandlePhysics(float elapsedTime)
        {
            conn.InternalCallReducer(new Reducer.HandlePhysics(elapsedTime), this.SetCallReducerFlags.HandlePhysicsFlags);
        }

        public bool InvokeHandlePhysics(ReducerEventContext ctx, Reducer.HandlePhysics args)
        {
            if (OnHandlePhysics == null) return false;
            OnHandlePhysics(
                ctx,
                args.ElapsedTime
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HandlePhysics : Reducer, IReducerArgs
        {
            [DataMember(Name = "elapsedTime")]
            public float ElapsedTime;

            public HandlePhysics(float ElapsedTime)
            {
                this.ElapsedTime = ElapsedTime;
            }

            public HandlePhysics()
            {
            }

            string IReducerArgs.ReducerName => "HandlePhysics";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags HandlePhysicsFlags;
        public void HandlePhysics(CallReducerFlags flags) => HandlePhysicsFlags = flags;
    }
}
