// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void JumpHandler(ReducerEventContext ctx, float angle);
        public event JumpHandler? OnJump;

        public void Jump(float angle)
        {
            conn.InternalCallReducer(new Reducer.Jump(angle), this.SetCallReducerFlags.JumpFlags);
        }

        public bool InvokeJump(ReducerEventContext ctx, Reducer.Jump args)
        {
            if (OnJump == null) return false;
            OnJump(
                ctx,
                args.Angle
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Jump : Reducer, IReducerArgs
        {
            [DataMember(Name = "angle")]
            public float Angle;

            public Jump(float Angle)
            {
                this.Angle = Angle;
            }

            public Jump()
            {
            }

            string IReducerArgs.ReducerName => "Jump";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags JumpFlags;
        public void Jump(CallReducerFlags flags) => JumpFlags = flags;
    }
}
