// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ResetHandler(ReducerEventContext ctx);
        public event ResetHandler? OnReset;

        public void Reset()
        {
            conn.InternalCallReducer(new Reducer.Reset(), this.SetCallReducerFlags.ResetFlags);
        }

        public bool InvokeReset(ReducerEventContext ctx, Reducer.Reset args)
        {
            if (OnReset == null) return false;
            OnReset(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Reset : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "Reset";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ResetFlags;
        public void Reset(CallReducerFlags flags) => ResetFlags = flags;
    }
}
