// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetshootingAngleHandler(ReducerEventContext ctx, float newAngle);
        public event SetshootingAngleHandler? OnSetshootingAngle;

        public void SetshootingAngle(float newAngle)
        {
            conn.InternalCallReducer(new Reducer.SetshootingAngle(newAngle), this.SetCallReducerFlags.SetshootingAngleFlags);
        }

        public bool InvokeSetshootingAngle(ReducerEventContext ctx, Reducer.SetshootingAngle args)
        {
            if (OnSetshootingAngle == null) return false;
            OnSetshootingAngle(
                ctx,
                args.NewAngle
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetshootingAngle : Reducer, IReducerArgs
        {
            [DataMember(Name = "newAngle")]
            public float NewAngle;

            public SetshootingAngle(float NewAngle)
            {
                this.NewAngle = NewAngle;
            }

            public SetshootingAngle()
            {
            }

            string IReducerArgs.ReducerName => "SetshootingAngle";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetshootingAngleFlags;
        public void SetshootingAngle(CallReducerFlags flags) => SetshootingAngleFlags = flags;
    }
}
