// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ShootWeaponHandler(ReducerEventContext ctx, uint wormId);
        public event ShootWeaponHandler? OnShootWeapon;

        public void ShootWeapon(uint wormId)
        {
            conn.InternalCallReducer(new Reducer.ShootWeapon(wormId), this.SetCallReducerFlags.ShootWeaponFlags);
        }

        public bool InvokeShootWeapon(ReducerEventContext ctx, Reducer.ShootWeapon args)
        {
            if (OnShootWeapon == null) return false;
            OnShootWeapon(
                ctx,
                args.WormId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ShootWeapon : Reducer, IReducerArgs
        {
            [DataMember(Name = "wormId")]
            public uint WormId;

            public ShootWeapon(uint WormId)
            {
                this.WormId = WormId;
            }

            public ShootWeapon()
            {
            }

            string IReducerArgs.ReducerName => "ShootWeapon";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ShootWeaponFlags;
        public void ShootWeapon(CallReducerFlags flags) => ShootWeaponFlags = flags;
    }
}
